// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protobuff2/transaction.proto

package pr2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data Message for request and response biller/switch
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bit 003 = Processing Code
	Bit_003 string `protobuf:"bytes,1,opt,name=bit_003,json=bit003,proto3" json:"bit_003,omitempty"`
	// bit 004 = Amount, Transaction
	Bit_004 string `protobuf:"bytes,2,opt,name=bit_004,json=bit004,proto3" json:"bit_004,omitempty"`
	// bit 005 = Mark Up Total
	Bit_005 string `protobuf:"bytes,3,opt,name=bit_005,json=bit005,proto3" json:"bit_005,omitempty"`
	// bit 006 = Profit Excluded
	Bit_006 string `protobuf:"bytes,4,opt,name=bit_006,json=bit006,proto3" json:"bit_006,omitempty"`
	// bit 007 = Biaya Layanan
	Bit_007 string `protobuf:"bytes,5,opt,name=bit_007,json=bit007,proto3" json:"bit_007,omitempty"`
	// bit 008 = Profit Included
	Bit_008 string `protobuf:"bytes,6,opt,name=bit_008,json=bit008,proto3" json:"bit_008,omitempty"`
	// bit 009 = Jumlah Tagihan
	Bit_009 string `protobuf:"bytes,7,opt,name=bit_009,json=bit009,proto3" json:"bit_009,omitempty"`
	// bit 011 = STAN
	Bit_011 string `protobuf:"bytes,8,opt,name=bit_011,json=bit011,proto3" json:"bit_011,omitempty"`
	// bit 012 = Time, Local Transaction
	Bit_012 string `protobuf:"bytes,9,opt,name=bit_012,json=bit012,proto3" json:"bit_012,omitempty"`
	// bit 013 = Partner Ref Number
	Bit_013 string `protobuf:"bytes,10,opt,name=bit_013,json=bit013,proto3" json:"bit_013,omitempty"`
	// bit 018 = Merchant Type
	Bit_018 string `protobuf:"bytes,11,opt,name=bit_018,json=bit018,proto3" json:"bit_018,omitempty"`
	// bit 026 = Additional Data - 001
	Bit_026 string `protobuf:"bytes,12,opt,name=bit_026,json=bit026,proto3" json:"bit_026,omitempty"`
	// bit 032 = Acquiring Institution Code
	Bit_032 string `protobuf:"bytes,13,opt,name=bit_032,json=bit032,proto3" json:"bit_032,omitempty"`
	// bit 037 = Additional Data - 002
	Bit_037 string `protobuf:"bytes,14,opt,name=bit_037,json=bit037,proto3" json:"bit_037,omitempty"`
	// bit 039 = Response Code (RC)
	Bit_039 string `protobuf:"bytes,15,opt,name=bit_039,json=bit039,proto3" json:"bit_039,omitempty"`
	// bit 040 = Additional Data - 003
	Bit_040 string `protobuf:"bytes,16,opt,name=bit_040,json=bit040,proto3" json:"bit_040,omitempty"`
	// bit 041 = Source Of Fund Identificator (Phone Number)
	Bit_041 string `protobuf:"bytes,17,opt,name=bit_041,json=bit041,proto3" json:"bit_041,omitempty"`
	// bit 042 = Device / Apps Identificator
	Bit_042 string `protobuf:"bytes,18,opt,name=bit_042,json=bit042,proto3" json:"bit_042,omitempty"`
	// bit 043 = Source Of Fund Identificator (Account Number)
	Bit_043 string `protobuf:"bytes,19,opt,name=bit_043,json=bit043,proto3" json:"bit_043,omitempty"`
	// bit 047 = Message
	Bit_047 string `protobuf:"bytes,20,opt,name=bit_047,json=bit047,proto3" json:"bit_047,omitempty"`
	// bit 048 = Additional Data - Public
	Bit_048 string `protobuf:"bytes,21,opt,name=bit_048,json=bit048,proto3" json:"bit_048,omitempty"`
	// bit 061 = Additional Data - Private
	Bit_061 string `protobuf:"bytes,22,opt,name=bit_061,json=bit061,proto3" json:"bit_061,omitempty"`
	// bit 100 = Biller Code
	Bit_100 string `protobuf:"bytes,23,opt,name=bit_100,json=bit100,proto3" json:"bit_100,omitempty"`
	// bit 103 = Account ID (ID Pelanggan)
	Bit_103 string `protobuf:"bytes,24,opt,name=bit_103,json=bit103,proto3" json:"bit_103,omitempty"`
	// bit 104 = Product Code
	Bit_104       string `protobuf:"bytes,25,opt,name=bit_104,json=bit104,proto3" json:"bit_104,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protobuff2_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff2_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protobuff2_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBit_003() string {
	if x != nil {
		return x.Bit_003
	}
	return ""
}

func (x *Message) GetBit_004() string {
	if x != nil {
		return x.Bit_004
	}
	return ""
}

func (x *Message) GetBit_005() string {
	if x != nil {
		return x.Bit_005
	}
	return ""
}

func (x *Message) GetBit_006() string {
	if x != nil {
		return x.Bit_006
	}
	return ""
}

func (x *Message) GetBit_007() string {
	if x != nil {
		return x.Bit_007
	}
	return ""
}

func (x *Message) GetBit_008() string {
	if x != nil {
		return x.Bit_008
	}
	return ""
}

func (x *Message) GetBit_009() string {
	if x != nil {
		return x.Bit_009
	}
	return ""
}

func (x *Message) GetBit_011() string {
	if x != nil {
		return x.Bit_011
	}
	return ""
}

func (x *Message) GetBit_012() string {
	if x != nil {
		return x.Bit_012
	}
	return ""
}

func (x *Message) GetBit_013() string {
	if x != nil {
		return x.Bit_013
	}
	return ""
}

func (x *Message) GetBit_018() string {
	if x != nil {
		return x.Bit_018
	}
	return ""
}

func (x *Message) GetBit_026() string {
	if x != nil {
		return x.Bit_026
	}
	return ""
}

func (x *Message) GetBit_032() string {
	if x != nil {
		return x.Bit_032
	}
	return ""
}

func (x *Message) GetBit_037() string {
	if x != nil {
		return x.Bit_037
	}
	return ""
}

func (x *Message) GetBit_039() string {
	if x != nil {
		return x.Bit_039
	}
	return ""
}

func (x *Message) GetBit_040() string {
	if x != nil {
		return x.Bit_040
	}
	return ""
}

func (x *Message) GetBit_041() string {
	if x != nil {
		return x.Bit_041
	}
	return ""
}

func (x *Message) GetBit_042() string {
	if x != nil {
		return x.Bit_042
	}
	return ""
}

func (x *Message) GetBit_043() string {
	if x != nil {
		return x.Bit_043
	}
	return ""
}

func (x *Message) GetBit_047() string {
	if x != nil {
		return x.Bit_047
	}
	return ""
}

func (x *Message) GetBit_048() string {
	if x != nil {
		return x.Bit_048
	}
	return ""
}

func (x *Message) GetBit_061() string {
	if x != nil {
		return x.Bit_061
	}
	return ""
}

func (x *Message) GetBit_100() string {
	if x != nil {
		return x.Bit_100
	}
	return ""
}

func (x *Message) GetBit_103() string {
	if x != nil {
		return x.Bit_103
	}
	return ""
}

func (x *Message) GetBit_104() string {
	if x != nil {
		return x.Bit_104
	}
	return ""
}

var File_protobuff2_transaction_proto protoreflect.FileDescriptor

const file_protobuff2_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobuff2/transaction.proto\x12\vtransaction\"\xfa\x04\n" +
	"\aMessage\x12\x17\n" +
	"\abit_003\x18\x01 \x01(\tR\x06bit003\x12\x17\n" +
	"\abit_004\x18\x02 \x01(\tR\x06bit004\x12\x17\n" +
	"\abit_005\x18\x03 \x01(\tR\x06bit005\x12\x17\n" +
	"\abit_006\x18\x04 \x01(\tR\x06bit006\x12\x17\n" +
	"\abit_007\x18\x05 \x01(\tR\x06bit007\x12\x17\n" +
	"\abit_008\x18\x06 \x01(\tR\x06bit008\x12\x17\n" +
	"\abit_009\x18\a \x01(\tR\x06bit009\x12\x17\n" +
	"\abit_011\x18\b \x01(\tR\x06bit011\x12\x17\n" +
	"\abit_012\x18\t \x01(\tR\x06bit012\x12\x17\n" +
	"\abit_013\x18\n" +
	" \x01(\tR\x06bit013\x12\x17\n" +
	"\abit_018\x18\v \x01(\tR\x06bit018\x12\x17\n" +
	"\abit_026\x18\f \x01(\tR\x06bit026\x12\x17\n" +
	"\abit_032\x18\r \x01(\tR\x06bit032\x12\x17\n" +
	"\abit_037\x18\x0e \x01(\tR\x06bit037\x12\x17\n" +
	"\abit_039\x18\x0f \x01(\tR\x06bit039\x12\x17\n" +
	"\abit_040\x18\x10 \x01(\tR\x06bit040\x12\x17\n" +
	"\abit_041\x18\x11 \x01(\tR\x06bit041\x12\x17\n" +
	"\abit_042\x18\x12 \x01(\tR\x06bit042\x12\x17\n" +
	"\abit_043\x18\x13 \x01(\tR\x06bit043\x12\x17\n" +
	"\abit_047\x18\x14 \x01(\tR\x06bit047\x12\x17\n" +
	"\abit_048\x18\x15 \x01(\tR\x06bit048\x12\x17\n" +
	"\abit_061\x18\x16 \x01(\tR\x06bit061\x12\x17\n" +
	"\abit_100\x18\x17 \x01(\tR\x06bit100\x12\x17\n" +
	"\abit_103\x18\x18 \x01(\tR\x06bit103\x12\x17\n" +
	"\abit_104\x18\x19 \x01(\tR\x06bit1042\xf4\x01\n" +
	"\x12TransactionService\x125\n" +
	"\aInquiry\x12\x14.transaction.Message\x1a\x14.transaction.Message\x129\n" +
	"\vTransaction\x12\x14.transaction.Message\x1a\x14.transaction.Message\x126\n" +
	"\bReversal\x12\x14.transaction.Message\x1a\x14.transaction.Message\x124\n" +
	"\x06Advice\x12\x14.transaction.Message\x1a\x14.transaction.MessageB#Z!github.com/didirdt/proto_test/pr2b\x06proto3"

var (
	file_protobuff2_transaction_proto_rawDescOnce sync.Once
	file_protobuff2_transaction_proto_rawDescData []byte
)

func file_protobuff2_transaction_proto_rawDescGZIP() []byte {
	file_protobuff2_transaction_proto_rawDescOnce.Do(func() {
		file_protobuff2_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff2_transaction_proto_rawDesc), len(file_protobuff2_transaction_proto_rawDesc)))
	})
	return file_protobuff2_transaction_proto_rawDescData
}

var file_protobuff2_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuff2_transaction_proto_goTypes = []any{
	(*Message)(nil), // 0: transaction.Message
}
var file_protobuff2_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.TransactionService.Inquiry:input_type -> transaction.Message
	0, // 1: transaction.TransactionService.Transaction:input_type -> transaction.Message
	0, // 2: transaction.TransactionService.Reversal:input_type -> transaction.Message
	0, // 3: transaction.TransactionService.Advice:input_type -> transaction.Message
	0, // 4: transaction.TransactionService.Inquiry:output_type -> transaction.Message
	0, // 5: transaction.TransactionService.Transaction:output_type -> transaction.Message
	0, // 6: transaction.TransactionService.Reversal:output_type -> transaction.Message
	0, // 7: transaction.TransactionService.Advice:output_type -> transaction.Message
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuff2_transaction_proto_init() }
func file_protobuff2_transaction_proto_init() {
	if File_protobuff2_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff2_transaction_proto_rawDesc), len(file_protobuff2_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff2_transaction_proto_goTypes,
		DependencyIndexes: file_protobuff2_transaction_proto_depIdxs,
		MessageInfos:      file_protobuff2_transaction_proto_msgTypes,
	}.Build()
	File_protobuff2_transaction_proto = out.File
	file_protobuff2_transaction_proto_goTypes = nil
	file_protobuff2_transaction_proto_depIdxs = nil
}
