// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protobuff/transaction.proto

package protobuff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Processingcode   string                 `protobuf:"bytes,1,opt,name=processingcode,proto3" json:"processingcode,omitempty"`     // bit 003
	Amount           string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`                     // bit 004
	Markuptotal      string                 `protobuf:"bytes,3,opt,name=markuptotal,proto3" json:"markuptotal,omitempty"`           // bit 005
	Profitex         string                 `protobuf:"bytes,4,opt,name=profitex,proto3" json:"profitex,omitempty"`                 // bit 006
	Transmissiontime string                 `protobuf:"bytes,5,opt,name=transmissiontime,proto3" json:"transmissiontime,omitempty"` // bit 007
	Profitin         string                 `protobuf:"bytes,6,opt,name=profitin,proto3" json:"profitin,omitempty"`                 // bit 008
	Jumlahtagihan    string                 `protobuf:"bytes,7,opt,name=jumlahtagihan,proto3" json:"jumlahtagihan,omitempty"`       // bit 009
	Stan             string                 `protobuf:"bytes,8,opt,name=stan,proto3" json:"stan,omitempty"`                         // bit 011
	Datetime         string                 `protobuf:"bytes,9,opt,name=datetime,proto3" json:"datetime,omitempty"`                 // bit 012
	Date             string                 `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`                        // bit 013
	Merchanttype     string                 `protobuf:"bytes,11,opt,name=merchanttype,proto3" json:"merchanttype,omitempty"`        // bit 018
	Poscc            string                 `protobuf:"bytes,12,opt,name=poscc,proto3" json:"poscc,omitempty"`                      // bit 026
	Bankcode         string                 `protobuf:"bytes,13,opt,name=bankcode,proto3" json:"bankcode,omitempty"`                // bit 032
	Noreference      string                 `protobuf:"bytes,14,opt,name=noreference,proto3" json:"noreference,omitempty"`          // bit 037
	Responsecode     string                 `protobuf:"bytes,15,opt,name=responsecode,proto3" json:"responsecode,omitempty"`        // bit 039
	Serviceres       string                 `protobuf:"bytes,16,opt,name=serviceres,proto3" json:"serviceres,omitempty"`            // bit 040
	Phonenumber      string                 `protobuf:"bytes,17,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`          // bit 041
	Deviceid         string                 `protobuf:"bytes,18,opt,name=deviceid,proto3" json:"deviceid,omitempty"`                // bit 042
	Accountnumber    string                 `protobuf:"bytes,19,opt,name=accountnumber,proto3" json:"accountnumber,omitempty"`      // bit 043
	Msg              string                 `protobuf:"bytes,20,opt,name=msg,proto3" json:"msg,omitempty"`                          // bit 047
	Msgresponse      string                 `protobuf:"bytes,21,opt,name=msgresponse,proto3" json:"msgresponse,omitempty"`          // bit 048
	Pin              string                 `protobuf:"bytes,22,opt,name=pin,proto3" json:"pin,omitempty"`                          // bit 061
	Billercode       string                 `protobuf:"bytes,23,opt,name=billercode,proto3" json:"billercode,omitempty"`            // bit 100
	Subscriberid     string                 `protobuf:"bytes,24,opt,name=subscriberid,proto3" json:"subscriberid,omitempty"`        // bit 103
	Productcode      string                 `protobuf:"bytes,25,opt,name=productcode,proto3" json:"productcode,omitempty"`          // bit 104
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protobuff_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protobuff_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetProcessingcode() string {
	if x != nil {
		return x.Processingcode
	}
	return ""
}

func (x *Message) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Message) GetMarkuptotal() string {
	if x != nil {
		return x.Markuptotal
	}
	return ""
}

func (x *Message) GetProfitex() string {
	if x != nil {
		return x.Profitex
	}
	return ""
}

func (x *Message) GetTransmissiontime() string {
	if x != nil {
		return x.Transmissiontime
	}
	return ""
}

func (x *Message) GetProfitin() string {
	if x != nil {
		return x.Profitin
	}
	return ""
}

func (x *Message) GetJumlahtagihan() string {
	if x != nil {
		return x.Jumlahtagihan
	}
	return ""
}

func (x *Message) GetStan() string {
	if x != nil {
		return x.Stan
	}
	return ""
}

func (x *Message) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Message) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Message) GetMerchanttype() string {
	if x != nil {
		return x.Merchanttype
	}
	return ""
}

func (x *Message) GetPoscc() string {
	if x != nil {
		return x.Poscc
	}
	return ""
}

func (x *Message) GetBankcode() string {
	if x != nil {
		return x.Bankcode
	}
	return ""
}

func (x *Message) GetNoreference() string {
	if x != nil {
		return x.Noreference
	}
	return ""
}

func (x *Message) GetResponsecode() string {
	if x != nil {
		return x.Responsecode
	}
	return ""
}

func (x *Message) GetServiceres() string {
	if x != nil {
		return x.Serviceres
	}
	return ""
}

func (x *Message) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *Message) GetDeviceid() string {
	if x != nil {
		return x.Deviceid
	}
	return ""
}

func (x *Message) GetAccountnumber() string {
	if x != nil {
		return x.Accountnumber
	}
	return ""
}

func (x *Message) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Message) GetMsgresponse() string {
	if x != nil {
		return x.Msgresponse
	}
	return ""
}

func (x *Message) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *Message) GetBillercode() string {
	if x != nil {
		return x.Billercode
	}
	return ""
}

func (x *Message) GetSubscriberid() string {
	if x != nil {
		return x.Subscriberid
	}
	return ""
}

func (x *Message) GetProductcode() string {
	if x != nil {
		return x.Productcode
	}
	return ""
}

var File_protobuff_transaction_proto protoreflect.FileDescriptor

const file_protobuff_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1bprotobuff/transaction.proto\x12\vtransaction\"\x85\x06\n" +
	"\aMessage\x12&\n" +
	"\x0eprocessingcode\x18\x01 \x01(\tR\x0eprocessingcode\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12 \n" +
	"\vmarkuptotal\x18\x03 \x01(\tR\vmarkuptotal\x12\x1a\n" +
	"\bprofitex\x18\x04 \x01(\tR\bprofitex\x12*\n" +
	"\x10transmissiontime\x18\x05 \x01(\tR\x10transmissiontime\x12\x1a\n" +
	"\bprofitin\x18\x06 \x01(\tR\bprofitin\x12$\n" +
	"\rjumlahtagihan\x18\a \x01(\tR\rjumlahtagihan\x12\x12\n" +
	"\x04stan\x18\b \x01(\tR\x04stan\x12\x1a\n" +
	"\bdatetime\x18\t \x01(\tR\bdatetime\x12\x12\n" +
	"\x04date\x18\n" +
	" \x01(\tR\x04date\x12\"\n" +
	"\fmerchanttype\x18\v \x01(\tR\fmerchanttype\x12\x14\n" +
	"\x05poscc\x18\f \x01(\tR\x05poscc\x12\x1a\n" +
	"\bbankcode\x18\r \x01(\tR\bbankcode\x12 \n" +
	"\vnoreference\x18\x0e \x01(\tR\vnoreference\x12\"\n" +
	"\fresponsecode\x18\x0f \x01(\tR\fresponsecode\x12\x1e\n" +
	"\n" +
	"serviceres\x18\x10 \x01(\tR\n" +
	"serviceres\x12 \n" +
	"\vphonenumber\x18\x11 \x01(\tR\vphonenumber\x12\x1a\n" +
	"\bdeviceid\x18\x12 \x01(\tR\bdeviceid\x12$\n" +
	"\raccountnumber\x18\x13 \x01(\tR\raccountnumber\x12\x10\n" +
	"\x03msg\x18\x14 \x01(\tR\x03msg\x12 \n" +
	"\vmsgresponse\x18\x15 \x01(\tR\vmsgresponse\x12\x10\n" +
	"\x03pin\x18\x16 \x01(\tR\x03pin\x12\x1e\n" +
	"\n" +
	"billercode\x18\x17 \x01(\tR\n" +
	"billercode\x12\"\n" +
	"\fsubscriberid\x18\x18 \x01(\tR\fsubscriberid\x12 \n" +
	"\vproductcode\x18\x19 \x01(\tR\vproductcode2\xf4\x01\n" +
	"\x12TransactionService\x125\n" +
	"\aInquiry\x12\x14.transaction.Message\x1a\x14.transaction.Message\x129\n" +
	"\vTransaction\x12\x14.transaction.Message\x1a\x14.transaction.Message\x126\n" +
	"\bReversal\x12\x14.transaction.Message\x1a\x14.transaction.Message\x124\n" +
	"\x06Advice\x12\x14.transaction.Message\x1a\x14.transaction.MessageB)Z'github.com/didirdt/proto_test/protobuffb\x06proto3"

var (
	file_protobuff_transaction_proto_rawDescOnce sync.Once
	file_protobuff_transaction_proto_rawDescData []byte
)

func file_protobuff_transaction_proto_rawDescGZIP() []byte {
	file_protobuff_transaction_proto_rawDescOnce.Do(func() {
		file_protobuff_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff_transaction_proto_rawDesc), len(file_protobuff_transaction_proto_rawDesc)))
	})
	return file_protobuff_transaction_proto_rawDescData
}

var file_protobuff_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuff_transaction_proto_goTypes = []any{
	(*Message)(nil), // 0: transaction.Message
}
var file_protobuff_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.TransactionService.Inquiry:input_type -> transaction.Message
	0, // 1: transaction.TransactionService.Transaction:input_type -> transaction.Message
	0, // 2: transaction.TransactionService.Reversal:input_type -> transaction.Message
	0, // 3: transaction.TransactionService.Advice:input_type -> transaction.Message
	0, // 4: transaction.TransactionService.Inquiry:output_type -> transaction.Message
	0, // 5: transaction.TransactionService.Transaction:output_type -> transaction.Message
	0, // 6: transaction.TransactionService.Reversal:output_type -> transaction.Message
	0, // 7: transaction.TransactionService.Advice:output_type -> transaction.Message
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuff_transaction_proto_init() }
func file_protobuff_transaction_proto_init() {
	if File_protobuff_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff_transaction_proto_rawDesc), len(file_protobuff_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_transaction_proto_goTypes,
		DependencyIndexes: file_protobuff_transaction_proto_depIdxs,
		MessageInfos:      file_protobuff_transaction_proto_msgTypes,
	}.Build()
	File_protobuff_transaction_proto = out.File
	file_protobuff_transaction_proto_goTypes = nil
	file_protobuff_transaction_proto_depIdxs = nil
}
