// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protobuff/transaction.proto

package protobuff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bit 003
	ProcessingCode string `protobuf:"bytes,1,opt,name=processing_code,json=processingCode,proto3" json:"processing_code,omitempty"`
	// bit 004
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// bit 005
	MarkupTotal string `protobuf:"bytes,3,opt,name=markup_total,json=markupTotal,proto3" json:"markup_total,omitempty"`
	// bit 006
	ProfitEx string `protobuf:"bytes,4,opt,name=profit_ex,json=profitEx,proto3" json:"profit_ex,omitempty"`
	// bit 007
	BiayaLayanan string `protobuf:"bytes,5,opt,name=biaya_layanan,json=biayaLayanan,proto3" json:"biaya_layanan,omitempty"`
	// bit 008
	ProfitIn string `protobuf:"bytes,6,opt,name=profit_in,json=profitIn,proto3" json:"profit_in,omitempty"`
	// bit 009
	JumlahTagihan string `protobuf:"bytes,7,opt,name=jumlah_tagihan,json=jumlahTagihan,proto3" json:"jumlah_tagihan,omitempty"`
	// bit 011
	Stan string `protobuf:"bytes,8,opt,name=stan,proto3" json:"stan,omitempty"`
	// bit 012
	Datetime string `protobuf:"bytes,9,opt,name=datetime,proto3" json:"datetime,omitempty"`
	// bit 013
	PartnerRef string `protobuf:"bytes,10,opt,name=partner_ref,json=partnerRef,proto3" json:"partner_ref,omitempty"`
	// bit 018
	MerchantType string `protobuf:"bytes,11,opt,name=merchant_type,json=merchantType,proto3" json:"merchant_type,omitempty"`
	// bit 026
	Additional_1 string `protobuf:"bytes,12,opt,name=additional_1,json=additional1,proto3" json:"additional_1,omitempty"`
	// bit 032
	BankCode string `protobuf:"bytes,13,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	// bit 037
	Additional_2 string `protobuf:"bytes,14,opt,name=additional_2,json=additional2,proto3" json:"additional_2,omitempty"`
	// bit 039
	ResponseCode string `protobuf:"bytes,15,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	// bit 040
	Additional_3 string `protobuf:"bytes,16,opt,name=additional_3,json=additional3,proto3" json:"additional_3,omitempty"`
	// bit 041
	PhoneNumber string `protobuf:"bytes,17,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// bit 042
	DeviceId string `protobuf:"bytes,18,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// bit 043
	AccountNumber string `protobuf:"bytes,19,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// bit 047
	Msg string `protobuf:"bytes,20,opt,name=msg,proto3" json:"msg,omitempty"`
	// bit 048
	MsgResponse string `protobuf:"bytes,21,opt,name=msg_response,json=msgResponse,proto3" json:"msg_response,omitempty"`
	// bit 061
	Pin string `protobuf:"bytes,22,opt,name=pin,proto3" json:"pin,omitempty"`
	// bit 100
	BillerCode string `protobuf:"bytes,23,opt,name=biller_code,json=billerCode,proto3" json:"biller_code,omitempty"`
	// bit 103
	SubscriberId string `protobuf:"bytes,24,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// bit 104
	ProductCode   string `protobuf:"bytes,25,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protobuff_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protobuff_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetProcessingCode() string {
	if x != nil {
		return x.ProcessingCode
	}
	return ""
}

func (x *Message) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Message) GetMarkupTotal() string {
	if x != nil {
		return x.MarkupTotal
	}
	return ""
}

func (x *Message) GetProfitEx() string {
	if x != nil {
		return x.ProfitEx
	}
	return ""
}

func (x *Message) GetBiayaLayanan() string {
	if x != nil {
		return x.BiayaLayanan
	}
	return ""
}

func (x *Message) GetProfitIn() string {
	if x != nil {
		return x.ProfitIn
	}
	return ""
}

func (x *Message) GetJumlahTagihan() string {
	if x != nil {
		return x.JumlahTagihan
	}
	return ""
}

func (x *Message) GetStan() string {
	if x != nil {
		return x.Stan
	}
	return ""
}

func (x *Message) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Message) GetPartnerRef() string {
	if x != nil {
		return x.PartnerRef
	}
	return ""
}

func (x *Message) GetMerchantType() string {
	if x != nil {
		return x.MerchantType
	}
	return ""
}

func (x *Message) GetAdditional_1() string {
	if x != nil {
		return x.Additional_1
	}
	return ""
}

func (x *Message) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *Message) GetAdditional_2() string {
	if x != nil {
		return x.Additional_2
	}
	return ""
}

func (x *Message) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *Message) GetAdditional_3() string {
	if x != nil {
		return x.Additional_3
	}
	return ""
}

func (x *Message) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Message) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Message) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Message) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Message) GetMsgResponse() string {
	if x != nil {
		return x.MsgResponse
	}
	return ""
}

func (x *Message) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *Message) GetBillerCode() string {
	if x != nil {
		return x.BillerCode
	}
	return ""
}

func (x *Message) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *Message) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

var File_protobuff_transaction_proto protoreflect.FileDescriptor

const file_protobuff_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1bprotobuff/transaction.proto\x12\vtransaction\"\xab\x06\n" +
	"\aMessage\x12'\n" +
	"\x0fprocessing_code\x18\x01 \x01(\tR\x0eprocessingCode\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12!\n" +
	"\fmarkup_total\x18\x03 \x01(\tR\vmarkupTotal\x12\x1b\n" +
	"\tprofit_ex\x18\x04 \x01(\tR\bprofitEx\x12#\n" +
	"\rbiaya_layanan\x18\x05 \x01(\tR\fbiayaLayanan\x12\x1b\n" +
	"\tprofit_in\x18\x06 \x01(\tR\bprofitIn\x12%\n" +
	"\x0ejumlah_tagihan\x18\a \x01(\tR\rjumlahTagihan\x12\x12\n" +
	"\x04stan\x18\b \x01(\tR\x04stan\x12\x1a\n" +
	"\bdatetime\x18\t \x01(\tR\bdatetime\x12\x1f\n" +
	"\vpartner_ref\x18\n" +
	" \x01(\tR\n" +
	"partnerRef\x12#\n" +
	"\rmerchant_type\x18\v \x01(\tR\fmerchantType\x12!\n" +
	"\fadditional_1\x18\f \x01(\tR\vadditional1\x12\x1b\n" +
	"\tbank_code\x18\r \x01(\tR\bbankCode\x12!\n" +
	"\fadditional_2\x18\x0e \x01(\tR\vadditional2\x12#\n" +
	"\rresponse_code\x18\x0f \x01(\tR\fresponseCode\x12!\n" +
	"\fadditional_3\x18\x10 \x01(\tR\vadditional3\x12!\n" +
	"\fphone_number\x18\x11 \x01(\tR\vphoneNumber\x12\x1b\n" +
	"\tdevice_id\x18\x12 \x01(\tR\bdeviceId\x12%\n" +
	"\x0eaccount_number\x18\x13 \x01(\tR\raccountNumber\x12\x10\n" +
	"\x03msg\x18\x14 \x01(\tR\x03msg\x12!\n" +
	"\fmsg_response\x18\x15 \x01(\tR\vmsgResponse\x12\x10\n" +
	"\x03pin\x18\x16 \x01(\tR\x03pin\x12\x1f\n" +
	"\vbiller_code\x18\x17 \x01(\tR\n" +
	"billerCode\x12#\n" +
	"\rsubscriber_id\x18\x18 \x01(\tR\fsubscriberId\x12!\n" +
	"\fproduct_code\x18\x19 \x01(\tR\vproductCode2\xf4\x01\n" +
	"\x12TransactionService\x125\n" +
	"\aInquiry\x12\x14.transaction.Message\x1a\x14.transaction.Message\x129\n" +
	"\vTransaction\x12\x14.transaction.Message\x1a\x14.transaction.Message\x126\n" +
	"\bReversal\x12\x14.transaction.Message\x1a\x14.transaction.Message\x124\n" +
	"\x06Advice\x12\x14.transaction.Message\x1a\x14.transaction.MessageB)Z'github.com/didirdt/proto_test/protobuffb\x06proto3"

var (
	file_protobuff_transaction_proto_rawDescOnce sync.Once
	file_protobuff_transaction_proto_rawDescData []byte
)

func file_protobuff_transaction_proto_rawDescGZIP() []byte {
	file_protobuff_transaction_proto_rawDescOnce.Do(func() {
		file_protobuff_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff_transaction_proto_rawDesc), len(file_protobuff_transaction_proto_rawDesc)))
	})
	return file_protobuff_transaction_proto_rawDescData
}

var file_protobuff_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuff_transaction_proto_goTypes = []any{
	(*Message)(nil), // 0: transaction.Message
}
var file_protobuff_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.TransactionService.Inquiry:input_type -> transaction.Message
	0, // 1: transaction.TransactionService.Transaction:input_type -> transaction.Message
	0, // 2: transaction.TransactionService.Reversal:input_type -> transaction.Message
	0, // 3: transaction.TransactionService.Advice:input_type -> transaction.Message
	0, // 4: transaction.TransactionService.Inquiry:output_type -> transaction.Message
	0, // 5: transaction.TransactionService.Transaction:output_type -> transaction.Message
	0, // 6: transaction.TransactionService.Reversal:output_type -> transaction.Message
	0, // 7: transaction.TransactionService.Advice:output_type -> transaction.Message
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuff_transaction_proto_init() }
func file_protobuff_transaction_proto_init() {
	if File_protobuff_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff_transaction_proto_rawDesc), len(file_protobuff_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_transaction_proto_goTypes,
		DependencyIndexes: file_protobuff_transaction_proto_depIdxs,
		MessageInfos:      file_protobuff_transaction_proto_msgTypes,
	}.Build()
	File_protobuff_transaction_proto = out.File
	file_protobuff_transaction_proto_goTypes = nil
	file_protobuff_transaction_proto_depIdxs = nil
}
